[profile.default]
via_ir = true
solc_version = "0.8.21"

optimizer = true
optimizer_runs = 9_999_999

remappings = [
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/"
]

[fmt]
line_length = 100 

[profile.via-ir]
via_ir = true

[rpc_endpoints]
main = 'https://rpc.ankr.com/eth'
base = 'https://rpc.ankr.com/base'
poly = 'https://rpc.ankr.com/polygon'
opti = 'https://rpc.ankr.com/optimism'
arbi = 'https://rpc.ankr.com/arbitrum'
